# Generated by Django 5.0.9 on 2024-09-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
        migrations.RemoveField(
            model_name='redirectpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='redirectpage',
            name='target_page',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='RedirectPage',
        ),
    ]
