# Generated by Django 5.0.9 on 2024-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa_base', '0004_templatesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatesettings',
            options={'verbose_name_plural': 'Template Settings'},
        ),
        migrations.AddField(
            model_name='templatesettings',
            name='themecolor',
            field=models.CharField(default='blue', help_text='The theme color. This should match the base name of a css file in a static folder wibekwa/css', max_length=30, verbose_name='theme color'),
        ),
    ]
