# Generated by Django 5.0.9 on 2024-09-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wibekwa_base', '0005_alter_templatesettings_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateSettings',
        ),
    ]
